### ISSUE TITLE
Credit code sources

### ISSUE THREAD

**Issue by Pierce01** [luuxis/minecraft-java-core#4]
Hey there Luuxis, I'm a little surprised to see how much code you've taken from my project (MinecraftLauncher-core) without giving any credit. MinecraftLauncher-core is licensed under MIT, so you are required to credit everything you've taken from my project. If you need me to point out all the stolen code, I can.

> When you use an MIT licensed piece of software you’re allowing anyone to do whatever they want with your code with one caveat: The original author must be given credit.

Here's a fun little article that explains why giving credit to developers is a good thing to do. http://billpatrianakos.me/blog/2016/05/11/dont-steal-code/

**Comment by luuxis** [comment]
no problem, it's already planned. I haven't finished the code yet.

**Comment by Pierce01** [comment]
Thank you for updating your readme. I appreciate your cooperation.

**Comment by luuxis** [comment]
yes but it's not worth denigrating my work on your discord

**Comment by luuxis** [comment]
and if my intention was really not to mention you I would have passed the project in private

**Comment by luuxis** [comment]
if you want I would like to talk on discord so that we can clarify the thing I don't want to stay on bad terms

my discord is **Luuxis#4545**

**Comment by luuxis** [comment]
sending people from my discord to yours first was not a good idea that's why I asked them to delete their message, and I sincerely regret it

send me a friend request on discord (I don't know your discord tag) I would like us to talk to get back on good terms

and once again i'm really sorry
